CONFIG_PRINTK=y
CONFIG_LOG=y

# Enable Bluetooth Subsystem
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="ESP32-DeskKnob"
CONFIG_BT_DEVICE_APPEARANCE=960

# Security Manager Protocol (SMP) & Bonding
CONFIG_BT_SMP=y
CONFIG_BT_BONDABLE=y
CONFIG_BT_L2CAP_TX_BUF_COUNT=5

# Enable Non-Volatile Storage / Settings subsystem for BLE keys
CONFIG_FLASH=y
CONFIG_NVS=y
CONFIG_SETTINGS=y
CONFIG_BT_SETTINGS=y

# Device Information Service (DIS)
CONFIG_BT_DIS=y
CONFIG_BT_DIS_PNP=y
CONFIG_BT_DIS_MANUF_NAME=y
CONFIG_BT_DIS_MANUF_NAME_STR="DIY"
CONFIG_BT_DIS_MODEL_NUMBER=y
CONFIG_BT_DIS_MODEL_NUMBER_STR="DeskKnob-S3"